// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return android;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0UqmeFcTso50k0xt_HXgjWwvaG-VJ0fQ',
    appId: '1:778690384108:android:eee0d77626d1046ff5d5c9',
    messagingSenderId: '778690384108',
    projectId: 'ibn-al-nafis-1be9a',
    storageBucket: 'ibn-al-nafis-1be9a.appspot.com',
  );

  // static const FirebaseOptions ios = Fireb1:232521491921:android:9ef771279307a167e96cf0aseOptions(
  //   apiKey: 'AIzaSyDJoqkMo2azPgIfX2siQAgWWkkqGUodK3Q',
  //   appId: '1:522117168869:ios:d87f7e6ecf9cd17a63de0c',
  //   messagingSenderId: '522117168869',
  //   projectId: 'clefincode-erp',
  //   storageBucket: 'clefincode-erp.appspot.com',
  //   iosBundleId: 'com.clefincode.erp',
  // );
}
